# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b8d7d02d301800f295b6766455ccaf5db82092564fddb497749e769015614cbbe4e5db77ea154ceab7cfbb1e6417e22dbb5094899a7f52752cac7a67eb32928

test:
  secret_key_base: d69166bb3f40d48ccf2ee3ee8c75cc00b7d7c8b91200efb22de7aaec28522a7ed3f78cae10324da704710cf5770e099aac7c944b23e86ea408080cf50dcf565e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
